name: BackupSDK CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build -t backupsdk-server .

  portal:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: portal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Build Docker image
        run: docker build -t backupsdk-portal .